# Generated by Django 4.2.7 on 2023-12-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_alter_contact_notes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="contact",
            name="notes",
            field=models.TextField(default="Write Notes Here....", max_length=200),
        ),
    ]
